### ISSUE TITLE
A question about the model on different dataset

### ISSUE THREAD

**Issue by jhzhang19** [zhangweichen2006/SRDAN_Open#1]
Thank you for your great work.I have a question for you, How does the model perform on different lidar datasets, such as Kitti to nuscense or waymo? Have you done any related experiments?

**Comment by zhangweichen2006** [comment]
We didn't conduct experiments on Kitti to nuscenes or waymo but we have a Virtual to real dataset (PreSIL to kitti) experiment. Please have a look.
