### ISSUE TITLE
integration into official OpenPCDet repository

### ISSUE THREAD

**Issue by MartinHahner** [zhangweichen2006/SRDAN_Open#2]
Hi Weichen,
congratulations on your awesome work! 🥳 
I really enjoyed reading your paper 📄 and was glad to see that you used [OpenPCDet](https://github.com/open-mmlab/OpenPCDet) for your implementations. 
In my opinion, it would be awesome if your work could be merged into the official OpenPCDet repository.
@zhangweichen2006: What do you think?
Greets, Martin

**Comment by zhangweichen2006** [comment]
Thanks for your suggestion! Unfortunately, we are not planing to integrate our code at the moment as the version compatibility will be a bit messy. Sorry but thanks again for your interests!
