### ISSUE TITLE
Question about the ASTAR dataset

### ISSUE THREAD

**Issue by jihanyang** [zhangweichen2006/SRDAN_Open#3]
May I know how to access the ASTAR dataset？

**Comment by zhangweichen2006** [comment]
Hi Jihan,

You could ask Astar by sending an email to their Astar3D team, not sure if
their dataset is available or not though... I graduated a long time ago, so
I might don’t have the dataset in the University server now…

Best Regards,

Weichen

jihan.yang ***@***.***>于2022年9月6日 周二22:48写道：

**Comment by jihanyang** [comment]
Thanks so much.
